# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54c6c0c06329230ad910adda4079085bbbf526927c4ad6167de39d623bc9a6008fec184d90cac45c01262066baf0c0add9c9365ce8b91db3b3343b914903b1dc

test:
  secret_key_base: 5edd85e3186929e1b6b52ad8eb15764374d14d5623546bc7f25e3c1afda6ea3fe538b139f9672b0ac0c2c20f59603d9e7fc8e456633da6ffb39292f33dc1e50f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
